[package]
name = "gb-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb-core = { path = "../gb-core" }
env_logger = "0.9.0"
clap = "2.33.3"
sdl2 = "0.35.1"
