[package]
name = "gb-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.1"
gb-core = { path = "../gb-core" }
env_logger = "0.9.0"
